------------------------------------------------------------------------------
-- 1) Création de la table OWNER
------------------------------------------------------------------------------
CREATE TABLE OWNER (
    owner_id           NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_name         VARCHAR2(100) NOT NULL,
    contact_info       VARCHAR2(150),
    CONSTRAINT PK_OWNER PRIMARY KEY(owner_id)
);

------------------------------------------------------------------------------
-- 2) Création de la table CITY
------------------------------------------------------------------------------
CREATE TABLE CITY (
    city_id       NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    city_name     VARCHAR2(100) NOT NULL,
    code_postal   VARCHAR2(10),
    region        VARCHAR2(100),
    country       VARCHAR2(100),
    UNIQUE (city_name)
);

------------------------------------------------------------------------------
-- 3) Création de la table NEIGHBORHOOD
------------------------------------------------------------------------------
CREATE TABLE NEIGHBORHOOD (
    neighborhood_id   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    city_id           NUMBER NOT NULL,
    neighborhood_name VARCHAR2(100) NOT NULL,
    
    CONSTRAINT FK_NEIGHBORHOOD_CITY
        FOREIGN KEY (city_id)
        REFERENCES CITY(city_id),
        
    CONSTRAINT UQ_NEIGHBORHOOD UNIQUE (city_id, neighborhood_name)
);

------------------------------------------------------------------------------
-- 4) Création de la table PROPERTY
------------------------------------------------------------------------------
CREATE TABLE PROPERTY (
    property_id           NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    owner_id              NUMBER NOT NULL,
    address               VARCHAR2(200),
    property_type         VARCHAR2(50),
    number_of_rooms       NUMBER,
    total_living_area     NUMBER,
    lot_size              NUMBER,
    property_condition    VARCHAR2(50),
    listing_price         NUMBER,
    rental_or_sale        VARCHAR2(10),  -- 'rental' or 'sale'
    availability_date     DATE,
    exclusivity_tier      VARCHAR2(50),
    city_id               NUMBER,
    neighborhood_id       NUMBER,
    CONSTRAINT PK_PROPERTY PRIMARY KEY (property_id),
    CONSTRAINT FK_PROPERTY_OWNER 
        FOREIGN KEY (owner_id) REFERENCES OWNER(owner_id),
    CONSTRAINT FK_PROPERTY_CITY
        FOREIGN KEY (city_id) REFERENCES CITY(city_id),
    CONSTRAINT FK_PROPERTY_NEIGHBORHOOD
        FOREIGN KEY (neighborhood_id) REFERENCES NEIGHBORHOOD(neighborhood_id)
);

------------------------------------------------------------------------------
-- 5) Création de la table ANCILLARY_FACILITY
------------------------------------------------------------------------------
CREATE TABLE ANCILLARY_FACILITY (
    facility_id   NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id   NUMBER NOT NULL,
    facility_type VARCHAR2(100),
    description   VARCHAR2(200),
    CONSTRAINT PK_ANCILLARY_FACILITY PRIMARY KEY(facility_id),
    CONSTRAINT FK_FACILITY_PROPERTY 
        FOREIGN KEY(property_id) REFERENCES PROPERTY(property_id)
);

------------------------------------------------------------------------------
-- 6) Création de la table CLIENT
------------------------------------------------------------------------------
CREATE TABLE CLIENT (
    client_id     NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    client_name   VARCHAR2(100) NOT NULL,
    contact_info  VARCHAR2(150),
    CONSTRAINT PK_CLIENT PRIMARY KEY (client_id)
);

------------------------------------------------------------------------------
-- 7) Création de la table TOUR
------------------------------------------------------------------------------
CREATE TABLE TOUR (
    tour_id     NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id NUMBER NOT NULL,
    client_id   NUMBER NOT NULL,
    tour_date   DATE,
    comments    VARCHAR2(200),
    CONSTRAINT PK_TOUR PRIMARY KEY (tour_id),
    CONSTRAINT FK_TOUR_PROPERTY 
        FOREIGN KEY(property_id) REFERENCES PROPERTY(property_id),
    CONSTRAINT FK_TOUR_CLIENT 
        FOREIGN KEY(client_id) REFERENCES CLIENT(client_id)
);

------------------------------------------------------------------------------
-- 8) Création de la table TOUR_LOG
------------------------------------------------------------------------------
CREATE TABLE TOUR_LOG (
    log_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tour_id    NUMBER NOT NULL,
    log_date   DATE,
    message    VARCHAR2(200),
    CONSTRAINT FK_TOUR_LOG
        FOREIGN KEY (tour_id)
        REFERENCES TOUR(tour_id)
);

------------------------------------------------------------------------------
-- 9) Création de la table LUX_TRANSACTION
------------------------------------------------------------------------------
CREATE TABLE LUX_TRANSACTION (
    transaction_id     NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    property_id        NUMBER NOT NULL,
    transaction_date   DATE NOT NULL,
    transaction_amount NUMBER NOT NULL,
    commission_amount  NUMBER,
    fiscal_period      VARCHAR2(20),
    CONSTRAINT PK_TRANSACTION PRIMARY KEY (transaction_id),
    CONSTRAINT FK_TRANSACTION_PROPERTY 
        FOREIGN KEY(property_id) REFERENCES PROPERTY(property_id)
);
